### ISSUE TITLE
Outlook: MAPI documentation is incorrect for 64-bit

### ISSUE THREAD

**Issue by zunzster** [MicrosoftDocs/office-developer-client-docs#51]
Just looking at the MAPI documentation and it doesn't consistently reflect all the changes to MAPI for 64-bit support.

For example, the documentation for IMAPIForm::Advise and IMAPIForm::Unadvise lists the ulConnection parameter as being a ULONG whereas Mapiforms.h in the Microsoft MAPI Headers declares it as ULONG_PTR.

**Comment by zunzster** [comment]
Another example, I just found after checking more of the ULONG to ULONG_PTR 32-bit to 64-bit changes.

IXPLogon::StartMessage, IPXLogon::SubmitMessage, IPXLogon::EndMessage also misdocument the ulMsgRef/pulMsgRef and pulReturnParm as ULONG rather than ULONG_PTR.

**Comment by zunzster** [comment]
IMAPISession::ShowForm and IMAPISession::PrepareForm misdocument ulMessageToken/lpulMessageToken as ULONG rather than ULONG_PTR.

**Comment by Linda-Editor** [comment]
@zunzster Thanks for the feedback, Paul. We'll look into it...

**Comment by Linda-Editor** [comment]
@Reezaali Can you direct this to the right person? Thanks...

**Comment by lindalu-MSFT** [comment]
@zunzster Hi, picking up where Linda-Editor left off... do you have a link to the documentation (I assume it's Outlook) where you encounter the doc errors? And also, if you have steps to repro, that would be helpful as well. We might need to direct this question to another repro to get a SME to respond.

**Comment by lindalu-MSFT** [comment]
Hi, @zunzster It occurs to me that since currently don't have anyone monitoring this repro, if you still would like a subject matter expert to triage and assist, please go to [https://github.com/OfficeDev/outlook-dev-docs](https://github.com/OfficeDev/outlook-dev-docs) and open an issue there. It will be triaged within a day or two, there. I'll close this issue here, sorry I can't transfer it but it's in a different org (OfficeDev instead of MicrosoftDocs.) Thanks!
